### ISSUE TITLE
Using CoovaChilli without internet access

### ISSUE THREAD

**Issue by denizerdi** [coova/coova-chilli#212]
Hello 

I am trying to make an offline media server with raspberry Pi. And i want to redirect people to the main page (IP of the device) when they connect to it through wifi hotspot. I managed to install coova and it works when Pi is connect to internet through eth0. But when i unplug the eth cable it doesnt work. I think i need to install a dns server inside Pi and make coova use it. But i cant seem to do this. Can anyone help me please?

Thanks

**Comment by gbaligh** [comment]
Can you try to force coovachilli to resolve only for local domain ?
```
"uamaliasip" - "Special IP Address aliased (redirect) to uamlisten/uamport" 
"uamaliasname" - "Special simple hostname (no dots) to be resolved to uamaliasip"
"uamhostname"  - "Special simple hostname (no dots) to be resolved to uamlisten"
"domaindnslocal" - "Option to consider all hostnames in domain as local"

```

**Comment by denizerdi** [comment]
HS_UAMALIASNAME=

will i add like this to the config file in chilli?

**Comment by denizerdi** [comment]
My whole purpose is actually just triggering something that is gonna redirect people when they connect to wifi or type another adress. ATM I don't need an authorization system.

**Comment by gbaligh** [comment]
The client must issue a HTTP request to be redirected, and it can only send HTTP if the DNS server respond.
So, What I'm suggesting is to try to resolve all FQDN suffixed by the localdomain to the uamlisten address.
Client will try to resolve FQDN directly, if this fail it will try to resolve FQDN.localdomain.
Just an idea.

**Comment by denizerdi** [comment]
Thanks for your answers. I am still trying and i discovered something. I unplugged ADSL cable from my router but Pi is still connected to it via eth0. So no internet access (in coova config dns are google dns). When i connect to wi-fi coova works great. Whatever i type i am still redirected to coova login page. So i am guessing my modem somehow is acting like a DNS server?

**Comment by muratbeser** [comment]
Deniz use iptables for redirecting users for 80 
If you want just a media server and dont want to serve any wifi hotspot service I think it's a good solution.

**Comment by sevan** [comment]
Hi,
There is now [a mailing list for questions such as these](https://www.brightonchilli.org.uk/mailman/listinfo/coovachilli), the issues section will be used solely for bug reports in code from now on, can I ask you to subscribe & take the discussion there (give it a few days as the system is freshly setup without any subscribers at the moment).

**Comment by antoniovalenzuela** [comment]
add 2 zones into local DNS (bind server too resolves on UAMLISTEN IP, Port UDP 53)

Example
HS_UAMLISTEN=10.10.10.1
HS_DNS1=10.10.10.1

Windows 8.1 and earlier versions --> zone: msftncsi.com
www IN A 190.46.255.40 (or any public IP)

Windows 10 and above ---> zone: msftconnecttest.com
www IN A 13.107.4.52 (or any public IP)

190.46.255.40 and 13.107.4.52 are the real IP addresses of each URL. It does not matter that you do not have internet, since coovachili always responds to TCP ports 80 for any IP (not dropped on a Firewall or IPTABLES)

In this way the DNS resolves the IP addresses and the browser redirects the page.

Windows 10 it works perfect.

I have scrips that check the status of the internet, so when there is no connection it redirects to an "internet temporarily out of service" page. The captive portal also has several interventions according to the needs of my clients.

![hspot](https://user-images.githubusercontent.com/28113584/39340055-25acb39a-49a2-11e8-86c7-5b04fac9a80c.jpg)

**Comment by s13884** [comment]
@denizerdi Can you help me to configure it without internet? Also does it still sending the login page of coova when no ethernet attached to pi?
