### ISSUE TITLE
compile OpenWrt

### ISSUE THREAD

**Issue by xADMx** [coova/coova-chilli#239]
Prompt how to compile, step by step in the OpenWrt

**Comment by Spomky** [comment]
You have to prepare your environment by installing needed tools on your plateform. The explanation [on this page](https://wiki.openwrt.org/doc/howto/buildroot.exigence) is quite simple to follow, but you are right: a dedicated page that shows step by step process is needed.

When everything is ready, you have to configure OpenWRT depending on the target device (x86, Ralink, AR71xx...) and enable the coova-chilli module: `make menuconfig`.

The problem is that the package proposed by the official OpenWRT repository is based on an outdated version.
I am modifying that package to provide a more recent version including almost all options. You can see that package on [my repository](https://github.com/Wi-Ho/packages).

**Comment by xADMx** [comment]
Good afternoon! I ore understand what to do and I ask you for help, you can make a video as you compile CoovaChilli???

**Comment by sevan** [comment]
Hi,
There is now [a mailing list for questions such as these](https://www.brightonchilli.org.uk/mailman/listinfo/coovachilli), the issues section will be used solely for bug reports in code from now on, can I ask you to subscribe & take the discussion there (give it a few days as the system is freshly setup without any subscribers at the moment).
