### ISSUE TITLE
IPSEC VPN can't be established through coova

### ISSUE THREAD

**Issue by PFELAVALESIEA** [coova/coova-chilli#301]
Hi, 
We are trying to mount an IPSEC VPN through coova-chilli, but the connection can not be established.

We analized network frames with Wireshark and we could see that
without coova the VPN could be established 
![ipsec sans coova](https://cloud.githubusercontent.com/assets/23341437/20108328/f5bfbb3e-a5db-11e6-8a78-62c109f7a101.PNG)

but when we use coova one frame was missing. 
![ipsec avec coova](https://cloud.githubusercontent.com/assets/23341437/20108333/faa6937a-a5db-11e6-9b6f-12ba1427331f.PNG)

Then we analized coova's logs and we saw that line: "coova-chilli[7807]: invalid UDP packet 1500 / 2056 / 1500"

Then we looked into coova's source code we identified that the line came from there (in /src/chilli.c):
![chili_code](https://cloud.githubusercontent.com/assets/23341437/20108561/bce38fba-a5dc-11e6-84a8-3505a08e6502.png)

We are still investigating but if someone can help us that would be great and we are available if you need more information.

Thanks a lot.

**Comment by nzamps** [comment]
Perhaps you need to add some more iptables rules.  Maybe:

iptables -I FORWARD -p udp --dport 4500 -j ACCEPT

**Comment by PFELAVALESIEA** [comment]
We already checked our iptables rules and udp port 4500 is open. Moreover, firsts ISAKMP frames passed well on that port.
We also see that someone had the same unresolved issue : #255

**Comment by Cool34000** [comment]
Hi,

I use this fix for Cisco VPN Client since a while and it works for me...
Don't know if this could help. Try adding this to your iptables:
iptables -I FORWARD 1 -i $HS_LANIF -p udp --dport 500 -j DROP
iptables -I FORWARD 2 -i $HS_LANIF -p udp --dport 4500 -j DROP
iptables -I PREROUTING 1 -t raw -i $TUNTAP   -p udp --dport 500 -j ACCEPT
iptables -I PREROUTING 2 -t raw -i $TUNTAP   -p udp --dport 4500 -j ACCEPT

**Comment by gbaligh** [comment]
Hi, 

The problem is in the code !

In fact, according to my understanding, if the IPv4 datagram is fragmented, the UDP header will indicate all the datagram length, but the IPv4 header will contains only the fragment size.
The condition `ntohs(udph->len) > ip_len` is always true in this case !

![image](https://cloud.githubusercontent.com/assets/5298640/20170095/29a6057a-a72b-11e6-8390-d5809f6f9965.png)

We need to add a test over the IPv4 flags, to check if the flag MF is set or not.

Try this patch:
`
if (udph && !iphdr_more_frag((struct pkt_iphdr_t*)ipph) && (ntohs(udph->len) > ip_len)) {
`

**Comment by PFELAVALESIEA** [comment]
Hi,
We tried gbaligh's patch and it works ! Our IPSec VPN mount.
Thanks everybody for your help !
