### ISSUE TITLE
Adding walled garden entry for a specific session over Http Request

### ISSUE THREAD

**Issue by chirayu-patel** [coova/coova-chilli#355]
I have a usecase where I want to add walled garden entry per session.. Is that possible right now ? I guess the current Login Url : '10.1.0.1:3990/logon?username=xxxx&password=xxxx' doesnt accept any such parameter..

But the good thing is I checked the chilli_query - they do support this facility .. Can we bring the same facility to the http request..

Would be highly appreciated.. Thanks !!

**Comment by wlanmac** [comment]
It wouldn't be good to have walled garden entries added to the /logon?.. URL since that isn't 'authenticated' (users could add their own garden entries). It can, however, be done via RADIUS - during MAC authentication, for example, while still returning AccessReject (so that the user gets the captive portal, just with a per-session walled garden). 

https://github.com/coova/coova-chilli/blob/4bc8334cb147d4b64d4fc1f89c66cdfef6ed517b/src/chilli.c#L4115

**Comment by chirayu-patel** [comment]
Hi David,

Can we get connected on skype to discuss further on both the issues that I have raised - 355 (the facebook thing) and the 391(wifi roaming part) . My skype id is : chirayu.patel9

Thanks.
