### ISSUE TITLE
Miniportal Refactor

### ISSUE THREAD

**Issue by pinkra** [coova/coova-chilli#66]
I think we can refactor the miniportal using html+js.. with the help of @mpangrazzi! What do you think @wlanmac @sevan ?

**Comment by mpangrazzi** [comment]
:+1:

IMHO, it would be great to deprecate haserl, and use directly [Pepper](https://github.com/mpangrazzi/pepper) for logon (CHAP/PAP) on a modern HTML5 UI, with all JS code in a [Browserify](http://browserify.org) bundle.

**Comment by muratbeser** [comment]
Pepper is a great tool but I think we need something minimal, with less dependency, 
I'm using AngularJS in my project so Pepper requires others  stuff too.

**Comment by wlanmac** [comment]
I like the angular js idea!

**Comment by mpangrazzi** [comment]
:-1: 

I'm sorry, but I don't like it.

Since miniportal is a _simple_ app, IMHO it's better to stay away from JS frameworks and write clean, modular code with vanilla JS and tools like Browserify. 

This way, users who don't know AngularJS (or whatever) could understand better the code flow and build up their own personal solution with ease.

@muratbeser Pepper has only three dependencies and no browser-compat issues. Also, [you can easily integrate Pepper in any AngularJS apps using Browserify](http://benclinkinbeard.com/talks/2014/ng-conf/).

**Comment by Spomky** [comment]
I agree with @mpangrazzi 
Please keep in mind that coovachilli is also installed on routeurs with small memory and should be as light as possible.This kind of project is great, but adds a lot of dependencies. It may be part of a third party package IMHO.

**Comment by muratbeser** [comment]
I'm Agree with @Spomky but I think we need pure javascript with OOP some people like me can customize it. Also we can make two examples with examples they can understand the progress. 

@mpangrazzi  yes I saw it but issue all about minimal dependency requirement approach also more dependency means more BC.

**Comment by pinkra** [comment]
@mpangrazzi Will it take long?

**Comment by sevan** [comment]
Happy to go with what you guys think is best here.

**Comment by mpangrazzi** [comment]
@pinkra I'm sorry but I haven't had much free time slots in the last month. Also, I still have to add PAP support to Pepper. BTW, it's not a long task, I hope to have more free time in the next month! 

I'll keep you updated.

**Comment by pinkra** [comment]
Don't worry, just to be updated ;)
