### ISSUE TITLE
Using custom app for authentication with CoovaChilli / freeRadius

### ISSUE THREAD

**Issue by apadliya** [coova/coova-chilli#97]
I have a pre-built app in Python Django that authenticates users using Social login (facebook  / google). I want to use this app to Authenticate users. Basically, i want to provide internet access to anyone who logs in to facebook and then goes through phone number verification via OTP. I have CoovaChilli on my router and have setup a freeRadius server. Can you please help me to figure out how to make freeRadius server work with this python app. Alternatively, would it be easier to make my Python app interact directly with Coovachilli, and if yes then how ?

**Comment by mpangrazzi** [comment]
Hi, for doing something like that you need to authenticate your users on RADIUS if their Facebook / Google login is successful. For authenticating on RADIUS, you have to dial with CoovaChilli, and you can easily doing that integrating [Pepper](https://github.com/mpangrazzi/pepper) on the client side of your Django app.

**Comment by bingyunxl** [comment]
Use chilli's openID

**Comment by cmoibal** [comment]
You can code a new module, and this module will authenticate all users, using any other methodes: Like using database to access client information and state.

**Comment by sevan** [comment]
Hi,
There is now [a mailing list for questions such as these](https://www.brightonchilli.org.uk/mailman/listinfo/coovachilli), the issues section will be used solely for bug reports in code from now on, can I ask you to subscribe & take the discussion there if this question is still valid. (It's been a while since the ticket was opened & a while since there was a reply)
